name: Validate Nix Flake

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  archive-download-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Run the archive download tests for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run build
        run: nix build -L .#default
  source-build-check-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Run the grlx CLI build tests for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run build
        run: nix build -L .#grlx-cli
  source-build-check-farmer:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Run the grlx farmer build tests for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run build
        run: nix build -L .#grlx-farmer
  source-build-check-sprout:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Run the grlx sprout build tests for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run build
        run: nix build -L .#grlx-sprout
  source-build-check-all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Run the grlx all build tests for ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run build
        run: nix build -L .#all
